### PR TITLE
add title to links on the html content

### PR DESCRIPTION
**Pull request by asmega**
but not the markdown version
so editors mousing over links in the editor can see the url

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1: 

Question though, how does this get reflected in the feed, i.e. the ruby MD -> HTML parser?

**Comment by asmega** [comment]
it won't. it uses the markdown. this only affects the HTML editor by adding the title. the markdown version will not have the title added. does that make sense?

**Comment by benbarnett** [comment]
So does the title already get added to the actual HTML rendered on the site? I guess that's what I'm asking.

**Comment by benbarnett** [comment]
Discussed offline... this is a 'CMS editor only' feature.

All good :+1:

**Comment by Guntrisoft** [comment]
:+1:

**Pull request merged**
